-- PRD v3: link bulk-shipment vendors and support internal cost estimates.
ALTER TABLE public.shipment_tracking
  ADD COLUMN IF NOT EXISTS vendor_id bigint REFERENCES public.vendors(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS shipment_tracking_vendor_id_idx
  ON public.shipment_tracking (vendor_id) WHERE vendor_id IS NOT NULL;

ALTER TABLE public.routes
  ADD COLUMN IF NOT EXISTS distance_km numeric;

CREATE TABLE IF NOT EXISTS public.internal_cost_model (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_type text NOT NULL UNIQUE,
  biaya_bbm_per_km numeric NOT NULL CHECK (biaya_bbm_per_km >= 0),
  biaya_overhead_flat numeric NOT NULL DEFAULT 0 CHECK (biaya_overhead_flat >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.internal_cost_model ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "authenticated read" ON public.internal_cost_model;
CREATE POLICY "authenticated read" ON public.internal_cost_model FOR SELECT TO authenticated USING (true);

